services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      - chatmat_net
    depends_on:
      - chatmat-back

  chatmat-back:
    build:
      context: ./
      dockerfile: ./chatmat-back/Dockerfile
    ports:
      - "9090:9090"
    networks:
      - chatmat_net

networks:
  chatmat_net:
    driver: bridge
